### ISSUE TITLE
Question about targeted confidence output

### ISSUE THREAD

**Issue by DHdroid** [nothingelse92/AnchorFace#1] opened 2021-02-04 06:06 UTC
Hello, I have a question about equation 5.
![image](https://user-images.githubusercontent.com/43927732/106851455-9e150680-66f9-11eb-86d2-79cc310583c1.png)

Based on equation 9 (Pearson coefficient < 0), I believe that the targeted confidence should have negative relation with the L2 distance between the anchor pose  and the ground-truth pose. If I am incorrect, would you mind providing me with an explanation as to why?

Thank you for your time and consideration :)

**Comment by nothingelse92** [comment] 2021-02-05 13:12
We sincerely apologize for the transcription error in Eq.5, it should be corrected as 
<img width="141" alt="截屏2021-02-05 下午9 06 30" src="https://user-images.githubusercontent.com/14359790/107037523-28429500-67f6-11eb-8fb8-8e4d724ec149.png">. We have revised our paper and uploaded it to the arxiv. Camera-ready version will be updated simultaneously. Thank you for your notice again, and our code will be released soon for reproduction.

**Comment by DHdroid** [comment] 2021-02-06 06:22
Thank you for a kind reply. But I believe that f(x)=tanh^-1(x) is also increasing function wrt x, so I think it should be f(x)=tanh(x^-1). If I am incorrect, would you mind providing me with an explanation?

Thank you.

**Comment by nothingelse92** [comment] 2021-02-06 06:50
Actually we intended to use tanh^-1 (x) in Eq5 to represent inverse tanh (x), which is a decreasing function. We will rewrite the formula to make it more clear in our paper.

**Closed as completed** 2021-02-07 08:24 UTC
